---
- name: Converge
  hosts: all
  become: true
  vars:
    FRANKLIN_MOLECULE_TEST: "true"
  tasks:
    - name: Set up
      import_role:
        name: common
    - name: Set up pi
      import_role:
        name: pi
    - name: Set up cluster
      import_role:
        name: cluster
