---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: cluster_node
    hostname: franklin
    image: ubuntu:latest
    # Do note that running containers in privileged mode is considerably less secure.
    privileged: true
    env:
      HOMELAB_MOLECULE_TEST: "true"
lint: |
  yamllint -c .yamllintrc ./
provisioner:
  name: ansible
  log: true
scenario:
  #become: true
  test_sequence:
    # - lint
    - destroy
    # - dependency
    - syntax
    - create
    - prepare
    - converge
    #- idempotence
    # - side_effect
    - verify
    # -destroy
verifier:
  name: testinfra
  lint:
    name: flake8
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
