---
- name: 'restart docker'
  service:
    name: docker
    state: restarted
  listen: 'restart docker service'

- name: restart slurmd
  service:
    name: slurmd
    state: restarted
  listen: 'restart slurmd service'

- name: 'restart slurmctld'
  service:
    name: slurmctld
    state: restarted
  listen: 'restart slurmctld service'

- name: 'restart munge'
  service:
    name: munge
    state: restarted
  listen: 'restart munge service'
