---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt -qq update
install:
  - python -m pip install -r python/requirements-test.txt
  - python -m pip install -r python/requirements.txt
script:
  - cd ansible/roles/dns && molecule syntax && cd -
  - cd ansible/roles/pi && molecule syntax && cd -
