---
#sudo apt-get purge wolfram-engine libreoffice* scratch -y
- name: 'Remove extra junk from Raspberry Pi'
  apt:
    purge: yes
    package: [ 'wolfram-engine', 'libreoffice*', 'scratch', 'bluej', 'greenfoot', 'nodered', 'minecraft-pi' ]
    state: absent
  tags: admin

# Remove X desktop
# sudo apt-get remove task-desktop -y
# sudo tasksel remove gnome-desktop
# sudo apt-get --purge autoremove -y  

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  tags: admin

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
    purge: yes
  tags: admin
