---
- name: Install python3-setuptools 
  apt:
    name: python3-setuptools
    state: latest
  when: ansible_os_family == "Debian"

- name: Install python3-pip
  apt:
    name: python3-pip
    state: latest
  when: ansible_os_family == "Debian"
