---
- name: 'Copy /etc/nsswitch.conf'
  copy:
    src: nsswitch.conf
    dest: /etc/nsswitch.conf
    mode: 0644

- name: 'Copy /etc/libnss-ldap.conf'
  copy:
    src: libnss-ldap.conf
    dest: /etc/libnss-ldap.conf
    mode: 0644

- name: 'Copy /etc/pam_ldap.conf'
  copy:
    src: pam_ldap.conf
    dest: /etc/pam_ldap.conf
    mode: 0644
