---
- name: install certificate authority packages
  apt:
    name:
      - easy-rsa
    force_apt_get: true
    update_cache: true

- name:
  lineinfile:
    dest: /etc/sysctl.conf
    line: "net.ipv4.ip_forward = 1"

# sysctl -p
