---
- name: Install packages
  include: packages.yml

- name: "Create /mnt/clusterfs directory"
  file:
    path: "/mnt/clusterfs"
    owner: 'nobody'
    group: 'nogroup'
    mode: 0755
    state: directory

- name: "Create /mnt/backup1 directory"
  file:
    path: "/mnt/backup1"
    owner: 'nobody'
    group: 'nogroup'
    mode: 0755
    state: directory
  
- name: 'Copy /etc/exports to fileserve2'
  copy:
    src: exports
    dest: /etc/exports
    mode: 0644
  when: "'fileserve2' in inventory_hostname"
  
#sudo exportfs â€“a
#sudo ufw allow from 10.10.8.0/21 to any port nfs
#sudo ufw status

- name: 'Copy /etc/exports to lanparty'
  copy:
    src: exports_lanparty
    dest: /etc/exports
    mode: 0644
  when: "'lanparty' in inventory_hostname"
