wget -O - https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install | sudo bash
wget -O - http://omv-extras.org/install | bash

gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv 7AA630A1EDEE7D73
gpg --export --armor 7AA630A1EDEE7D73 | sudo apt-key add -
apt update

systemctl status openmediavault-engined