---
- name: 'Install screensavers on Debian/Ubuntu'
  apt:
    package: [ 'xscreensaver-data-extra', 'xscreensaver-gl-extra', 'rss-glx' ]
    state: latest
  tags: admin
  when: ansible_os_family == "Debian"

- name: 'Install docker on Debian/Ubuntu'
  apt:
    package: [ 'apt-transport-https',
               'ca-certificates',
               'curl',
               'gnupg-agent',
               'software-properties-common',
               'docker-ce', 'docker-ce-cli', 'containerd.io', 'docker-compose' ]
    state: latest
  tags: admin
  when: ansible_os_family == "Debian"

- name: 'Install Python3 & Ruby on Debian/Ubuntu'
  apt:
    package: [ 'python3-pip', 'ruby' ]
    state: latest
  tags: admin
  when: ansible_os_family == "Debian"

- name: 'Install lolcat gem'
  gem:
    name: lolcat
    state: latest
    user_install: no
  with_items:
    - rake
    - lolcat

# Publishing tools sigil calibre
