---
- name: "Ansible Playbook for head nodes"
  hosts: head_nodes
  remote_user: root
  become: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  roles:
    - common
    - kerb_ldap
    - pi
