---
- name: 'Ansible Playbook for Media hosts'
  hosts: media
  remote_user: pi
  become: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  roles:
    - common
    - kerb_ldap
    - media
    - pi
