---
- name: 'Ansible Playbook for Raspi Cluster'
  hosts: raspi_cluster
  remote_user: pi
  become: yes
  max_fail_percentage: 50
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    logging_host: 10.10.12.14
  roles:
    - cluster
    - common
    - kerb_ldap
    - logging
    - pi
