---
- name: 'Ansible Playbook for Raspi Cluster'
  hosts: raspi_cluster
  remote_user: franklin
  become: yes
  max_fail_percentage: 50
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  roles:
    - cluster
    - common
    - kerb_ldap
    - pi
  environment:
    DEBIAN_FRONTEND: noninteractive

