---
- name: Ansible Playbook for Raspberry Pi hosts
  hosts: raspis
  remote_user: pi
  become: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    logging_host: 10.10.12.14
  roles:
    - common
    - kerb_ldap
    - logging
    - pi
