---

# /etc/krb5.conf is in the common playbook

- name: "Create /etc/krb5kdc folder"
  file:
    path: "/etc/krb5kdc"
    owner: "root"
    state: directory

- name: 'Copy /etc/krb5kdc/kdc.conf'
  copy:
    src: krb5.conf
    dest: /etc/krb5kdc/kdc.conf
    mode: 0664
