---
- name: 'Coopy /etc/ldap/ldap.conf'
  copy:
    src: ldap.conf
    dest: /etc/ldap/ldap.conf
    mode: 0644

- name: 'Copy /etc/default/slapd'
  copy:
    src: sldap
    dest: /etc/default/slapd
    mode: 0644

- name: 'Coopy /etc/ldap/sldap.conf'
  copy:
    src: sldap.conf
    dest: /etc/ldap/sldap.conf
    mode: 0644
