---
- name: Install krb5-kdc-ldap 
  apt:
    name: krb5-kdc-ldap
    state: latest

- name: Install krb5-admin-server
  apt:
    name: krb5-admin-server
    state: latest

- name: Install LDAP tools
  apt:
    package: ['slapd', 'schema2ldif', 'ldap-utils']
    state: latest
  tags: admin

  # ldap-schema-manager -i kerberos.schema

- name: 'Install Kerberos Packages'
  apt:
    package: [ 'sasl2-bin', 'libsasl2-2', 'libsasl2-modules', 'libsasl2-modules-gssapi-mit' ]
    state: latest
  tags: admin

- name: 'Install SASL Packages'
  apt:
    pacakge: [ 'sasl2-bin', 'libsasl2-2', libsasl2-modules', 'libsasl2-modules-gssapi-mit' ]
    state: latest
  tags: admin
