---
- name: 'Install Kerberos Packages'
  apt:
    package: [ 'krb5-kdc', 'krb5-admin-server', 'krb5-pkinit' ]
    state: latest
  tags: admin

- name: Install LDAP tools
  apt:
    package: ['slapd', 'schema2ldif', 'ldap-utils']
    state: latest
  tags: admin

  # ldap-schema-manager -i kerberos.schema

- name: 'Install SASL Packages'
  apt:
    package: [ 'sasl2-bin', 'libsasl2-2', 'libsasl2-modules', 'libsasl2-modules-gssapi-mit' ]
    state: latest
  tags: admin
